// pages/api/summarize.js
//
// AI Novel Summarizer backend.
// - If the requested novel matches a book already in /public (our own
//   library), we ground the summary in real extracted text from that PDF
//   (see data/book-texts.json, generated by scripts/extract-book-texts.js).
// - Otherwise, we fall back to the model's own general knowledge of the novel.
//
// Requires GEMINI_API_KEY set in Vercel's Environment Variables
// (free, no credit card: https://aistudio.google.com/app/apikey).

import { GoogleGenAI } from "@google/genai";
import bookTexts from "../../data/book-texts.json";

function normalize(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// Finds the best-matching local PDF for a given title/author, if any.
// Scores by how many of the query's significant words appear in the filename.
function findLocalMatch(title, author) {
  const queryWords = normalize(`${title} ${author || ""}`)
    .split(" ")
    .filter((w) => w.length > 2); // skip tiny words like "of", "a", "the"

  if (queryWords.length === 0) return null;

  let best = null;
  let bestScore = 0;

  for (const filename of Object.keys(bookTexts)) {
    const normalizedFilename = normalize(filename);
    const score = queryWords.filter((w) => normalizedFilename.includes(w)).length;
    if (score > bestScore) {
      bestScore = score;
      best = filename;
    }
  }

  // Require at least half the meaningful query words to match, so "Twain"
  // alone doesn't wrongly match an unrelated book.
  const threshold = Math.ceil(queryWords.length / 2);
  return bestScore >= threshold ? best : null;
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ message: "Method Not Allowed" });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ message: "Missing Gemini API Key" });
  }

  const { title, author } = req.body;
  if (!title || typeof title !== "string") {
    return res.status(400).json({ message: "A novel title is required" });
  }

  const matchedFile = findLocalMatch(title, author || "");
  const grounded = Boolean(matchedFile);
  const excerpt = grounded ? bookTexts[matchedFile] : null;

  const prompt = grounded
    ? `Using ONLY the following excerpt from the novel "${title}"${author ? ` by ${author}` : ""}, produce a study-guide style breakdown. If the excerpt doesn't cover the full novel, use your general knowledge of the complete story to fill in the rest, but prioritize what's in the excerpt for detail and accuracy.\n\nExcerpt:\n${excerpt}\n\nRespond with ONLY valid JSON, no markdown fences, no extra text, in this exact shape:\n{"plotSummary": "string, 3-5 sentences", "mainCharacters": [{"name": "string", "description": "string, one sentence"}], "themes": ["string", "..."], "setting": "string, one sentence"}`
    : `Provide a study-guide style breakdown of the novel "${title}"${author ? ` by ${author}` : ""} using your general knowledge. If you are not confident this novel exists or you don't have reliable knowledge of it, say so honestly in plotSummary instead of inventing details.\n\nRespond with ONLY valid JSON, no markdown fences, no extra text, in this exact shape:\n{"plotSummary": "string, 3-5 sentences", "mainCharacters": [{"name": "string", "description": "string, one sentence"}], "themes": ["string", "..."], "setting": "string, one sentence"}`;

  const ai = new GoogleGenAI({ apiKey });

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    const raw = response.text.trim();
    const cleaned = raw.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```$/i, "").trim();

    let parsed;
    try {
      parsed = JSON.parse(cleaned);
    } catch {
      return res.status(502).json({ message: "AI returned an unexpected format. Try again.", raw });
    }

    return res.status(200).json({
      title,
      author: author || null,
      grounded,
      source: grounded ? "BHS24HUB library" : "general knowledge",
      ...parsed,
    });
  } catch (error) {
    console.error("Summarizer error:", error);
    return res.status(500).json({ message: "Error generating summary", error: error.message || String(error) });
  }
}